version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:3000

  backend:
    build:
      context: ./backend/repaper
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/repaper:/app
    environment:
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=http://localhost:3000
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000

networks:
  default:
    name: repaper-network 